
// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyCU3mxQ5PvMtOsRi1S50ko0UK82kWJe7bo",
  authDomain: "chatbotapp46.firebaseapp.com",
  projectId: "chatbotapp46",
  storageBucket: "chatbotapp46.appspot.com",
  messagingSenderId: "449707000033",
  appId: "1:449707000033:web:63f9b202297d507f38f7a0"
};
// Initialize Firebase
firebase.initializeApp(firebaseConfig);

//46 回答配列(仮３つ)
Array[0]=0
Array[1]=1
Array[2]=3

const db=firebase.firestore();
const collection = db.collection('messagees');

//46 回答配列を約150個入れる(ループで書きたい。。)
collection.add({
  message1: Array[0],
  message2: Array[1],
  message3: Array[2],
  // message4: 'test',
  // message5: 'test',
  // message6: 'test',
  // message7: 'test',
  // message8: 'test',
  // message9: 'test',
  // message10: 'test',
  // message11: 'test',
  // message12: 'test',
  // message13: 'test',
  // message14: 'test',
  // message15: 'test',
  // message16: 'test',
  // message17: 'test',
  // message18: 'test',
  // message19: 'test',
  // message20: 'test',
  // message21: 'test',
  // message22: 'test',
  // message23: 'test',
  // message24: 'test',
  // message25: 'test',
  // message26: 'test',
  // message27: 'test',
  // message28: 'test',
  // message29: 'test',
  // message30: 'test',
  // message31: 'test',
  // message32: 'test',
  // message33: 'test',
  // message34: 'test',
  // message35: 'test',
  // message36: 'test',
  // message37: 'test',
  // message38: 'test',
  // message39: 'test',
  // message40: 'test',
  // message41: 'test',
  // message42: 'test',
  // message43: 'test',
  // message44: 'test',
  // message45: 'test',
  // message46: 'test',
  // message47: 'test',
  // message48: 'test',
  // message49: 'test',
  // message50: 'test',
  // message51: 'test',
  // message52: 'test',
  // message53: 'test',
  // message54: 'test',
  // message55: 'test',
  // message56: 'test',
  // message57: 'test',
  // message58: 'test',
  // message59: 'test',
  // message60: 'test',
  // message61: 'test',
  // message62: 'test',
  // message63: 'test',
  // message64: 'test',
  // message65: 'test',
  // message66: 'test',
  // message67: 'test',
  // message68: 'test',
  // message69: 'test',
  // message70: 'test',
  // message71: 'test',
  // message72: 'test',
  // message73: 'test',
  // message74: 'test',
  // message75: 'test',
  // message76: 'test',
  // message77: 'test',
  // message78: 'test',
  // message79: 'test',
  // message80: 'test',
  // message81: 'test',
  // message82: 'test',
  // message83: 'test',
  // message84: 'test',
  // message85: 'test',
  // message86: 'test',
  // message87: 'test',
  // message88: 'test',
  // message89: 'test',
  // message90: 'test',
  // message91: 'test',
  // message92: 'test',
  // message93: 'test',
  // message94: 'test',
  // message95: 'test',
  // message96: 'test',
  // message97: 'test',
  // message98: 'test',
  // message99: 'test',
  // message100: 'test',
  // message101: 'test',
  // message102: 'test',
  // message103: 'test',
  // message104: 'test',
  // message105: 'test',
  // message106: 'test',
  // message107: 'test',
  // message108: 'test',
  // message109: 'test',
  // message110: 'test',
  // message111: 'test',
  // message112: 'test',
  // message113: 'test',
  // message114: 'test',
  // message115: 'test',
  // message116: 'test',
  // message117: 'test',
  // message118: 'test',
  // message119: 'test',
  // message120: 'test',
  // message121: 'test',
  // message122: 'test',
  // message123: 'test',
  // message124: 'test',
  // message125: 'test',
  // message126: 'test',
  // message127: 'test',
  // message128: 'test',
  // message129: 'test',
  // message130: 'test',
  // message131: 'test',
  // message132: 'test',
  // message133: 'test',
  // message134: 'test',
  // message135: 'test',
  // message136: 'test',
  // message137: 'test',
  // message138: 'test',
  // message139: 'test',
  // message140: 'test',
  // message141: 'test',
  // message142: 'test',
  // message143: 'test',
  // message144: 'test',
  // message145: 'test',
  // message146: 'test',
  // message147: 'test',
  // message148: 'test',
  // message149: 'test',
  // message150: 'test',
  // message151: 'test',
  // message152: 'test',
  // message153: 'test',
  // message154: 'test',
  // message155: 'test',
  // message156: 'test',
  // message157: 'test',
  // message158: 'test',
  // message159: 'test',
  // message160: 'test',
  // message161: 'test',
  // message162: 'test',
  // message163: 'test',
  // message164: 'test',
  // message165: 'test'
  
})
.then(doc => {
console.log(`${doc.id} added!`)
})
